config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only:[:new, :create]
  resources :links, only:[:index, :create, :edit, :update, :new]

  namespace :api, default: {format: :json} do
    namespace :v1 do
      resources :links, only: [:update]
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, url: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true, :format => { :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  validates :password, presence: true

end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  respond_to :json

  def update
    respond_with Link.update(params[:id], link_params), location: nil
  end

  private

    def link_params
      params.permit(:read)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method (:current_user)

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @new_link = Link.new
    @links = Link.all.where(user_id: current_user.id)
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      @link.update_attribute(:user_id, current_user.id)
      flash[:success] = "You have saved a link!"
      redirect_to links_path
    else
      flash.now[:danger] = "Invalid Input"
      render :index
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
      if @link.update(link_params)
        redirect_to links_path
      else
        flash.now[:danger] = "Invalid Input"
        render :edit
      end
  end

private
  def link_params
    params.require(:link).permit(:title, :url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to links_path
    else
      flash.now[:danger] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Thank you for creating an account!"
      redirect_to links_path
    else
      flash.now[:danger] = "Invalid Input"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThoughtBox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Raleway' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<div class="link-form">
  <div class="text-center">
    <h1>Submit a link here</h1>
    <%= form_for(@link) do |f| %>
      <h4><%= f.label :title %></h4>
      <h4><%= f.text_field :title %></h4>
      <h4><%= f.label :url %></h4>
      <h4><%= f.text_field :url %></h4>
      <%= f.submit "Edit link", class: "btn btn-primary btn-font-size" %>
    <% end %>
  </div>
</div>

app/views/links/index.html.erb
<div class="container">
  <h4><%= link_to "Log out", logout_path, method: :delete, class: "btn btn-danger" %></h4>
  <div class="link-form">
    <div class="text-center">
      <h1>Submit a link here</h1>
      <%= form_for(@new_link) do |f| %>
        <h4><%= f.label :title %></h4>
        <h4><%= f.text_field :title %></h4>
        <h4><%= f.label :url %></h4>
        <h4><%= f.text_field :url %></h4>
        <%= f.submit "Submit link", class: "btn btn-primary btn-font-size" %>
      <% end %>
      <br><br>
    </div>
  </div>

  <div class="link-finder text-center">
    <input type="text" name="find-link" id="find-link" placeholder="find link">
    <button class="view-read btn btn-default">View Read Links</button>
    <button class="view-unread btn btn-default">View Unread Links</button>
  </div>

  <div class="user-links">
    <% @links.each do |link| %>
    <ul>
      <div class="link-content col-md-6 text-center" id= <%= "#{link.id}" %> data-id= <%= "#{link.read}" %>>
          <div class="link-text">
            <h4>Title: <%= link.title %></h4>
            <h5>Link: <%= link.url %></h5>
          </div>
            <%= link_to "Edit Link", edit_link_path(link.id) %>
            <div class="unread-link"><button class="btn btn-primary">Mark as Read</button></div>
            <div class="read-link"><button class="btn btn-default">Mark as Unread</button></div>
          </div>
    </ul>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="text-center">
    <h1>Please sign up for Thought Box</h1>
    <%= form_for(@user) do |f| %>
      <h4><%= f.label :email %></h4>
      <h4><%= f.email_field :email %></h4>
      <h4><%= f.label :password %></h4>
      <h4><%= f.password_field :password %></h4>
      <h4><%= f.label :password_confirmation %></h4>
      <h4><%= f.password_field :password_confirmation %></h4>
      <%= f.submit "Sign up", class: "btn btn-primary btn-font-size" %>
    <% end %>
  </div>
</div>